---
# This is created with Ubuntu 16.04 in mind.
# This would change for a different OS
- hosts: all
  become: yes
  roles:
    -  { role: init, tags: [ 'init'] }

- hosts: web
  become: yes
  roles:
    - { role: geerlingguy.php-versions, tags: [ 'php'] }
    - { role: geerlingguy.php, tags: [ 'php'] }
    - { role: geerlingguy.composer, tags: [ 'composer'] }
    - { role: geerlingguy.drush, tags: [ 'drush'] }
    - { role: geerlingguy.drupal-console, tags: [ 'drupal-console'] }
    - { role: geerlingguy.nginx, tags: [ 'nginx'] }

- hosts: db
  become: yes
  roles:
    - { role: geerlingguy.mysql, tags: [ 'mysql'] }
