---
- hosts: all
  become: no
  roles:
    - init

- hosts: web
  become: no
  roles:
    - geerlingguy.nginx
    - geerlingguy.php
    - geerlingguy.php-mysql
    - geerlingguy.php-pecl
    - geerlingguy.composer
    - geerlingguy.drush

- hosts: db
  become: no
  roles:
    - init
    - geerlingguy.mysql
