---
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.drush
  version: 3.0.0
- src: geerlingguy.drupal-console
  version: 1.1.0
- src: geerlingguy.firewall
  version: 2.3.0
- src: geerlingguy.mysql
  version: 2.8.2
- src: geerlingguy.nginx
  version: 2.5.0
- src: geerlingguy.php
  version: 3.5.1
- src: geerlingguy.php-mysql
  version: 2.0.1
- src: geerlingguy.php-pecl
  version: 1.4.0
- src: geerlingguy.php-xdebug
  version: 2.4.0
- src: geerlingguy.php-xhprof
  version: 2.2.2
- src: geerlingguy.postfix
  version: 2.0.0
- src: geerlingguy.security
  version: 1.6.0
- src: carlosbuenosvinos.ansistrano-deploy
  version: 2.8.0
- src: carlosbuenosvinos.ansistrano-rollback
  version: 2.0.1
