---
init_packages:
  - sudo
  - build-essential
  - python-software-properties
  - vim
  - curl
  - wget
  - mcrypt
  - git-core
  - git
  - zip
  - fail2ban
  - monit
  - sendmail

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

nginx_vhosts: []

php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_enable_webserver: false
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5
