---

- name: Ensure we have our website directory
  become: yes
  file:
    path: "{{ project_docroot_path }}/tmp/web"
    state: directory
    owner: "{{ project_deploy_owner }}"
    group: "{{ project_deploy_group }}"
    mode: 0755

- name: Ensure we have our website directory
  become: yes
  become_user: "{{ project_deploy_owner }}"
  file:
    src: "{{ project_docroot_path }}/tmp"
    dest: "{{ project_docroot_path }}/current"
    state: link
