---
init_packages:
  - sudo
  - build-essential
  - python-software-properties
  - vim
  - curl
  - wget
  - git-core
  - git
  - zip
  - fail2ban
  - monit
  - sendmail
  - mariadb-client

php_version: '7.1'
php_install_recommends: no
php_enable_webserver: no
php_packages:
  - php7.1
  - php7.1-common
  - php7.1-apcu
  - php7.1-cli
  - php7.1-curl
  - php7.1-dev
  - php7.1-fpm
  - php7.1-gd
  - php7.1-json
  - php7.1-mbstring
  - php7.1-mysql
  - php7.1-opcache
  - php7.1-pdo
  - php7.1-xml
  - php7.1-yaml

php_enable_php_fpm: true
php_fpm_daemon: 'php7.1-fpm'
php_fpm_listen: "127.0.0.1:9000"
php_fpm_listen_allowed_clients: "127.0.0.1"
php_fpm_pm_max_children: 50
php_fpm_pm_start_servers: 5
php_fpm_pm_min_spare_servers: 5
php_fpm_pm_max_spare_servers: 5

drush_launcher_install: yes
drush_launcher_version: '0.6.0'
