---
# Sends anonymous stats if the user is ok with it
- name: ANSISTRANO | Send anonymous stats
  uri:
    url: https://ansistrano.com/deploy
    follow_redirects: all
    method: POST
    timeout: 5
    body: "deploy_via={{ ansistrano_deploy_via | default('rsync') }}&version={{ ansible_version.string }}"
    HEADER_Content-Type: "application/x-www-form-urlencoded"
  when: ansistrano_allow_anonymous_stats
  run_once: true
  ignore_errors: yes
  delegate_to: 127.0.0.1
  become: false
