---

  - name: Check if project already exists
    stat:
      path: '{{ project_docroot_path }}/project'
    register: project

  - name: Output path is defined
    debug:
      msg: '{{ project_docroot_path }}/project path exists and do not touch anything else'
    when: project.stat.isdir is defined and project.stat.isdir

  - name: Output path is not defined
    debug:
      msg: '{{ project_docroot_path }}/project path does not exist. Set up site'
    when: project.stat.isdir is not defined

  - include: setup.yml
    when: project.stat.isdir is not defined

  - name: Update uploaded files directory permissions
    become: yes
    shell: 'chmod -R a-x+X {{ project_docroot_path}}/shared/web/sites/default/files && chmod -R ug+rws {{ project_docroot_path}}/shared/web/sites/default/files'

  - name: Restart nginx
    become: yes
    service:
      name: nginx
      state: restarted

  - name: Restart php{{ php_version }}-fpm
    become: yes
    service:
      name: php{{ php_version }}-fpm
      state: restarted
